// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: echo/v3/echo.proto

package echo

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         string                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_echo_v3_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_v3_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_echo_v3_echo_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMovie() string {
	if x != nil {
		return x.Movie
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movie         string                 `protobuf:"bytes,1,opt,name=movie,proto3" json:"movie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_echo_v3_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_v3_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_echo_v3_echo_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMovie() string {
	if x != nil {
		return x.Movie
	}
	return ""
}

var File_echo_v3_echo_proto protoreflect.FileDescriptor

const file_echo_v3_echo_proto_rawDesc = "" +
	"\n" +
	"\x12echo/v3/echo.proto\x12\aecho.v3\x1a\x1cgoogle/api/annotations.proto\"#\n" +
	"\vEchoRequest\x12\x14\n" +
	"\x05movie\x18\x01 \x01(\tR\x05movie\"$\n" +
	"\fEchoResponse\x12\x14\n" +
	"\x05movie\x18\x01 \x01(\tR\x05movie2\xf4\x02\n" +
	"\x04Echo\x12O\n" +
	"\vEchoMessage\x12\x14.echo.v3.EchoRequest\x1a\x15.echo.v3.EchoResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v3/echo\x12:\n" +
	"\tUnaryEcho\x12\x14.echo.v3.EchoRequest\x1a\x15.echo.v3.EchoResponse\"\x00\x12F\n" +
	"\x13ServerStreamingEcho\x12\x14.echo.v3.EchoRequest\x1a\x15.echo.v3.EchoResponse\"\x000\x01\x12F\n" +
	"\x13ClientStreamingEcho\x12\x14.echo.v3.EchoRequest\x1a\x15.echo.v3.EchoResponse\"\x00(\x01\x12O\n" +
	"\x1aBidirectionalStreamingEcho\x12\x14.echo.v3.EchoRequest\x1a\x15.echo.v3.EchoResponse\"\x00(\x010\x01B5Z3github.com/reaksa-maii/one_digital_grpc_getway/echob\x06proto3"

var (
	file_echo_v3_echo_proto_rawDescOnce sync.Once
	file_echo_v3_echo_proto_rawDescData []byte
)

func file_echo_v3_echo_proto_rawDescGZIP() []byte {
	file_echo_v3_echo_proto_rawDescOnce.Do(func() {
		file_echo_v3_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_v3_echo_proto_rawDesc), len(file_echo_v3_echo_proto_rawDesc)))
	})
	return file_echo_v3_echo_proto_rawDescData
}

var file_echo_v3_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_echo_v3_echo_proto_goTypes = []any{
	(*EchoRequest)(nil),  // 0: echo.v3.EchoRequest
	(*EchoResponse)(nil), // 1: echo.v3.EchoResponse
}
var file_echo_v3_echo_proto_depIdxs = []int32{
	0, // 0: echo.v3.Echo.EchoMessage:input_type -> echo.v3.EchoRequest
	0, // 1: echo.v3.Echo.UnaryEcho:input_type -> echo.v3.EchoRequest
	0, // 2: echo.v3.Echo.ServerStreamingEcho:input_type -> echo.v3.EchoRequest
	0, // 3: echo.v3.Echo.ClientStreamingEcho:input_type -> echo.v3.EchoRequest
	0, // 4: echo.v3.Echo.BidirectionalStreamingEcho:input_type -> echo.v3.EchoRequest
	1, // 5: echo.v3.Echo.EchoMessage:output_type -> echo.v3.EchoResponse
	1, // 6: echo.v3.Echo.UnaryEcho:output_type -> echo.v3.EchoResponse
	1, // 7: echo.v3.Echo.ServerStreamingEcho:output_type -> echo.v3.EchoResponse
	1, // 8: echo.v3.Echo.ClientStreamingEcho:output_type -> echo.v3.EchoResponse
	1, // 9: echo.v3.Echo.BidirectionalStreamingEcho:output_type -> echo.v3.EchoResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_v3_echo_proto_init() }
func file_echo_v3_echo_proto_init() {
	if File_echo_v3_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_v3_echo_proto_rawDesc), len(file_echo_v3_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_v3_echo_proto_goTypes,
		DependencyIndexes: file_echo_v3_echo_proto_depIdxs,
		MessageInfos:      file_echo_v3_echo_proto_msgTypes,
	}.Build()
	File_echo_v3_echo_proto = out.File
	file_echo_v3_echo_proto_goTypes = nil
	file_echo_v3_echo_proto_depIdxs = nil
}
