// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: podcast/v3/podcast.proto

package podcastv3

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Locale        string                 `protobuf:"bytes,3,opt,name=locale,proto3" json:"locale,omitempty"`
	DocumentId    string                 `protobuf:"bytes,4,opt,name=documentId,proto3" json:"documentId,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_podcast_v3_podcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_podcast_v3_podcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_podcast_v3_podcast_proto_rawDescGZIP(), []int{0}
}

func (x *Author) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *Author) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Author) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Author) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Author) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

type ListAuthorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// add pagination fields if needed
	Limit         int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsRequest) Reset() {
	*x = ListAuthorsRequest{}
	mi := &file_podcast_v3_podcast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsRequest) ProtoMessage() {}

func (x *ListAuthorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podcast_v3_podcast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsRequest.ProtoReflect.Descriptor instead.
func (*ListAuthorsRequest) Descriptor() ([]byte, []int) {
	return file_podcast_v3_podcast_proto_rawDescGZIP(), []int{1}
}

func (x *ListAuthorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuthorsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListAuthorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       []*Author              `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsResponse) Reset() {
	*x = ListAuthorsResponse{}
	mi := &file_podcast_v3_podcast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsResponse) ProtoMessage() {}

func (x *ListAuthorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podcast_v3_podcast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsResponse.ProtoReflect.Descriptor instead.
func (*ListAuthorsResponse) Descriptor() ([]byte, []int) {
	return file_podcast_v3_podcast_proto_rawDescGZIP(), []int{2}
}

func (x *ListAuthorsResponse) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

type GetAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthorRequest) Reset() {
	*x = GetAuthorRequest{}
	mi := &file_podcast_v3_podcast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthorRequest) ProtoMessage() {}

func (x *GetAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podcast_v3_podcast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return file_podcast_v3_podcast_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuthorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	DocumentId    string                 `protobuf:"bytes,3,opt,name=documentId,proto3" json:"documentId,omitempty"` // other fields as needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorRequest) Reset() {
	*x = CreateAuthorRequest{}
	mi := &file_podcast_v3_podcast_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorRequest) ProtoMessage() {}

func (x *CreateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podcast_v3_podcast_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_podcast_v3_podcast_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAuthorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAuthorRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *CreateAuthorRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

var File_podcast_v3_podcast_proto protoreflect.FileDescriptor

const file_podcast_v3_podcast_proto_rawDesc = "" +
	"\n" +
	"\x18podcast/v3/podcast.proto\x12\n" +
	"podcast.v3\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x02\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06locale\x18\x03 \x01(\tR\x06locale\x12\x1e\n" +
	"\n" +
	"documentId\x18\x04 \x01(\tR\n" +
	"documentId\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12<\n" +
	"\vpublishedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\"B\n" +
	"\x12ListAuthorsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"C\n" +
	"\x13ListAuthorsResponse\x12,\n" +
	"\aauthors\x18\x01 \x03(\v2\x12.podcast.v3.AuthorR\aauthors\"\"\n" +
	"\x10GetAuthorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"a\n" +
	"\x13CreateAuthorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\x12\x1e\n" +
	"\n" +
	"documentId\x18\x03 \x01(\tR\n" +
	"documentId2\xaa\x02\n" +
	"\rAuthorService\x12c\n" +
	"\vListAuthors\x12\x1e.podcast.v3.ListAuthorsRequest\x1a\x1f.podcast.v3.ListAuthorsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v3/authors\x12W\n" +
	"\tGetAuthor\x12\x1c.podcast.v3.GetAuthorRequest\x1a\x12.podcast.v3.Author\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v3/authors/{id}\x12[\n" +
	"\fCreateAuthor\x12\x1f.podcast.v3.CreateAuthorRequest\x1a\x12.podcast.v3.Author\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v3/authorsBBZ@github.com/reaksa-maii/one_digital_grpc_getway/podcast;podcastv3b\x06proto3"

var (
	file_podcast_v3_podcast_proto_rawDescOnce sync.Once
	file_podcast_v3_podcast_proto_rawDescData []byte
)

func file_podcast_v3_podcast_proto_rawDescGZIP() []byte {
	file_podcast_v3_podcast_proto_rawDescOnce.Do(func() {
		file_podcast_v3_podcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podcast_v3_podcast_proto_rawDesc), len(file_podcast_v3_podcast_proto_rawDesc)))
	})
	return file_podcast_v3_podcast_proto_rawDescData
}

var file_podcast_v3_podcast_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_podcast_v3_podcast_proto_goTypes = []any{
	(*Author)(nil),                // 0: podcast.v3.Author
	(*ListAuthorsRequest)(nil),    // 1: podcast.v3.ListAuthorsRequest
	(*ListAuthorsResponse)(nil),   // 2: podcast.v3.ListAuthorsResponse
	(*GetAuthorRequest)(nil),      // 3: podcast.v3.GetAuthorRequest
	(*CreateAuthorRequest)(nil),   // 4: podcast.v3.CreateAuthorRequest
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_podcast_v3_podcast_proto_depIdxs = []int32{
	5, // 0: podcast.v3.Author.createdAt:type_name -> google.protobuf.Timestamp
	5, // 1: podcast.v3.Author.updatedAt:type_name -> google.protobuf.Timestamp
	5, // 2: podcast.v3.Author.publishedAt:type_name -> google.protobuf.Timestamp
	0, // 3: podcast.v3.ListAuthorsResponse.authors:type_name -> podcast.v3.Author
	1, // 4: podcast.v3.AuthorService.ListAuthors:input_type -> podcast.v3.ListAuthorsRequest
	3, // 5: podcast.v3.AuthorService.GetAuthor:input_type -> podcast.v3.GetAuthorRequest
	4, // 6: podcast.v3.AuthorService.CreateAuthor:input_type -> podcast.v3.CreateAuthorRequest
	2, // 7: podcast.v3.AuthorService.ListAuthors:output_type -> podcast.v3.ListAuthorsResponse
	0, // 8: podcast.v3.AuthorService.GetAuthor:output_type -> podcast.v3.Author
	0, // 9: podcast.v3.AuthorService.CreateAuthor:output_type -> podcast.v3.Author
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_podcast_v3_podcast_proto_init() }
func file_podcast_v3_podcast_proto_init() {
	if File_podcast_v3_podcast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podcast_v3_podcast_proto_rawDesc), len(file_podcast_v3_podcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podcast_v3_podcast_proto_goTypes,
		DependencyIndexes: file_podcast_v3_podcast_proto_depIdxs,
		MessageInfos:      file_podcast_v3_podcast_proto_msgTypes,
	}.Build()
	File_podcast_v3_podcast_proto = out.File
	file_podcast_v3_podcast_proto_goTypes = nil
	file_podcast_v3_podcast_proto_depIdxs = nil
}
