// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: podcast/v1/podcat.proto

package podcatv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodcatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PodcatSize    string                 `protobuf:"bytes,2,opt,name=podcat_size,json=podcatSize,proto3" json:"podcat_size,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Duration      float64                `protobuf:"fixed64,6,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodcatRequest) Reset() {
	*x = PodcatRequest{}
	mi := &file_podcast_v1_podcat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodcatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodcatRequest) ProtoMessage() {}

func (x *PodcatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podcast_v1_podcat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodcatRequest.ProtoReflect.Descriptor instead.
func (*PodcatRequest) Descriptor() ([]byte, []int) {
	return file_podcast_v1_podcat_proto_rawDescGZIP(), []int{0}
}

func (x *PodcatRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PodcatRequest) GetPodcatSize() string {
	if x != nil {
		return x.PodcatSize
	}
	return ""
}

func (x *PodcatRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PodcatRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PodcatRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PodcatRequest) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type PodcatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PodcatSize    string                 `protobuf:"bytes,2,opt,name=podcat_size,json=podcatSize,proto3" json:"podcat_size,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Duration      float64                `protobuf:"fixed64,6,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodcatResponse) Reset() {
	*x = PodcatResponse{}
	mi := &file_podcast_v1_podcat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodcatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodcatResponse) ProtoMessage() {}

func (x *PodcatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_podcast_v1_podcat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodcatResponse.ProtoReflect.Descriptor instead.
func (*PodcatResponse) Descriptor() ([]byte, []int) {
	return file_podcast_v1_podcat_proto_rawDescGZIP(), []int{1}
}

func (x *PodcatResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PodcatResponse) GetPodcatSize() string {
	if x != nil {
		return x.PodcatSize
	}
	return ""
}

func (x *PodcatResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PodcatResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PodcatResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PodcatResponse) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type GetByTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByTitleRequest) Reset() {
	*x = GetByTitleRequest{}
	mi := &file_podcast_v1_podcat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByTitleRequest) ProtoMessage() {}

func (x *GetByTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podcast_v1_podcat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByTitleRequest.ProtoReflect.Descriptor instead.
func (*GetByTitleRequest) Descriptor() ([]byte, []int) {
	return file_podcast_v1_podcat_proto_rawDescGZIP(), []int{2}
}

func (x *GetByTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_podcast_v1_podcat_proto protoreflect.FileDescriptor

const file_podcast_v1_podcat_proto_rawDesc = "" +
	"\n" +
	"\x17podcast/v1/podcat.proto\x12\tpodcat.v1\x1a\x1cgoogle/api/annotations.proto\"\xb0\x01\n" +
	"\rPodcatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vpodcat_size\x18\x02 \x01(\tR\n" +
	"podcatSize\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x01R\bduration\"\xb1\x01\n" +
	"\x0ePodcatResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vpodcat_size\x18\x02 \x01(\tR\n" +
	"podcatSize\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x01R\bduration\")\n" +
	"\x11GetByTitleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title2\x9b\x04\n" +
	"\rPodcatService\x12[\n" +
	"\rCreatePodcast\x12\x18.podcat.v1.PodcatRequest\x1a\x19.podcat.v1.PodcatResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/podcat\x12g\n" +
	"\x10GetPodcatByTitle\x12\x1c.podcat.v1.GetByTitleRequest\x1a\x19.podcat.v1.PodcatResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/podcat/{title}\x12E\n" +
	"\fUnaryPodcast\x12\x18.podcat.v1.PodcatRequest\x1a\x19.podcat.v1.PodcatResponse\"\x00\x12P\n" +
	"\x15ServerStreamingPodcat\x12\x18.podcat.v1.PodcatRequest\x1a\x19.podcat.v1.PodcatResponse\"\x000\x01\x12P\n" +
	"\x15ClientStreamingPodcat\x12\x18.podcat.v1.PodcatRequest\x1a\x19.podcat.v1.PodcatResponse\"\x00(\x01\x12Y\n" +
	"\x1cBidirectionalStreamingPodcat\x12\x18.podcat.v1.PodcatRequest\x1a\x19.podcat.v1.PodcatResponse\"\x00(\x010\x01B@Z>github.com/reaksa-maii/one_digital_grpc_getway/podcat;podcatv1b\x06proto3"

var (
	file_podcast_v1_podcat_proto_rawDescOnce sync.Once
	file_podcast_v1_podcat_proto_rawDescData []byte
)

func file_podcast_v1_podcat_proto_rawDescGZIP() []byte {
	file_podcast_v1_podcat_proto_rawDescOnce.Do(func() {
		file_podcast_v1_podcat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podcast_v1_podcat_proto_rawDesc), len(file_podcast_v1_podcat_proto_rawDesc)))
	})
	return file_podcast_v1_podcat_proto_rawDescData
}

var file_podcast_v1_podcat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_podcast_v1_podcat_proto_goTypes = []any{
	(*PodcatRequest)(nil),     // 0: podcat.v1.PodcatRequest
	(*PodcatResponse)(nil),    // 1: podcat.v1.PodcatResponse
	(*GetByTitleRequest)(nil), // 2: podcat.v1.GetByTitleRequest
}
var file_podcast_v1_podcat_proto_depIdxs = []int32{
	0, // 0: podcat.v1.PodcatService.CreatePodcast:input_type -> podcat.v1.PodcatRequest
	2, // 1: podcat.v1.PodcatService.GetPodcatByTitle:input_type -> podcat.v1.GetByTitleRequest
	0, // 2: podcat.v1.PodcatService.UnaryPodcast:input_type -> podcat.v1.PodcatRequest
	0, // 3: podcat.v1.PodcatService.ServerStreamingPodcat:input_type -> podcat.v1.PodcatRequest
	0, // 4: podcat.v1.PodcatService.ClientStreamingPodcat:input_type -> podcat.v1.PodcatRequest
	0, // 5: podcat.v1.PodcatService.BidirectionalStreamingPodcat:input_type -> podcat.v1.PodcatRequest
	1, // 6: podcat.v1.PodcatService.CreatePodcast:output_type -> podcat.v1.PodcatResponse
	1, // 7: podcat.v1.PodcatService.GetPodcatByTitle:output_type -> podcat.v1.PodcatResponse
	1, // 8: podcat.v1.PodcatService.UnaryPodcast:output_type -> podcat.v1.PodcatResponse
	1, // 9: podcat.v1.PodcatService.ServerStreamingPodcat:output_type -> podcat.v1.PodcatResponse
	1, // 10: podcat.v1.PodcatService.ClientStreamingPodcat:output_type -> podcat.v1.PodcatResponse
	1, // 11: podcat.v1.PodcatService.BidirectionalStreamingPodcat:output_type -> podcat.v1.PodcatResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podcast_v1_podcat_proto_init() }
func file_podcast_v1_podcat_proto_init() {
	if File_podcast_v1_podcat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podcast_v1_podcat_proto_rawDesc), len(file_podcast_v1_podcat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podcast_v1_podcat_proto_goTypes,
		DependencyIndexes: file_podcast_v1_podcat_proto_depIdxs,
		MessageInfos:      file_podcast_v1_podcat_proto_msgTypes,
	}.Build()
	File_podcast_v1_podcat_proto = out.File
	file_podcast_v1_podcat_proto_goTypes = nil
	file_podcast_v1_podcat_proto_depIdxs = nil
}
