// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: movies/v1/movie.proto

package movie

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Movie         string                 `protobuf:"bytes,2,opt,name=movie,proto3" json:"movie,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Duration      float64                `protobuf:"fixed64,6,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieRequest) Reset() {
	*x = MovieRequest{}
	mi := &file_movies_v1_movie_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieRequest) ProtoMessage() {}

func (x *MovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_movies_v1_movie_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieRequest.ProtoReflect.Descriptor instead.
func (*MovieRequest) Descriptor() ([]byte, []int) {
	return file_movies_v1_movie_proto_rawDescGZIP(), []int{0}
}

func (x *MovieRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MovieRequest) GetMovie() string {
	if x != nil {
		return x.Movie
	}
	return ""
}

func (x *MovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MovieRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MovieRequest) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type MovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Movie         string                 `protobuf:"bytes,2,opt,name=movie,proto3" json:"movie,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Duration      float64                `protobuf:"fixed64,6,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieResponse) Reset() {
	*x = MovieResponse{}
	mi := &file_movies_v1_movie_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieResponse) ProtoMessage() {}

func (x *MovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movies_v1_movie_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieResponse.ProtoReflect.Descriptor instead.
func (*MovieResponse) Descriptor() ([]byte, []int) {
	return file_movies_v1_movie_proto_rawDescGZIP(), []int{1}
}

func (x *MovieResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MovieResponse) GetMovie() string {
	if x != nil {
		return x.Movie
	}
	return ""
}

func (x *MovieResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MovieResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MovieResponse) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_movies_v1_movie_proto protoreflect.FileDescriptor

const file_movies_v1_movie_proto_rawDesc = "" +
	"\n" +
	"\x15movies/v1/movie.proto\x12\bmovie.v1\x1a\x1cgoogle/api/annotations.proto\"\xa4\x01\n" +
	"\fMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05movie\x18\x02 \x01(\tR\x05movie\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x01R\bduration\"\xa5\x01\n" +
	"\rMovieResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05movie\x18\x02 \x01(\tR\x05movie\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x01R\bduration2\x8d\x03\n" +
	"\x05Movie\x12T\n" +
	"\vEchoMessage\x12\x16.movie.v1.MovieRequest\x1a\x17.movie.v1.MovieResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/movie\x12>\n" +
	"\tUnaryEcho\x12\x16.movie.v1.MovieRequest\x1a\x17.movie.v1.MovieResponse\"\x00\x12K\n" +
	"\x14ServerStreamingMovie\x12\x16.movie.v1.MovieRequest\x1a\x17.movie.v1.MovieResponse\"\x000\x01\x12K\n" +
	"\x14ClientStreamingMovie\x12\x16.movie.v1.MovieRequest\x1a\x17.movie.v1.MovieResponse\"\x00(\x01\x12T\n" +
	"\x1bBidirectionalStreamingMovie\x12\x16.movie.v1.MovieRequest\x1a\x17.movie.v1.MovieResponse\"\x00(\x010\x01B6Z4github.com/reaksa-maii/one_digital_grpc_getway/movieb\x06proto3"

var (
	file_movies_v1_movie_proto_rawDescOnce sync.Once
	file_movies_v1_movie_proto_rawDescData []byte
)

func file_movies_v1_movie_proto_rawDescGZIP() []byte {
	file_movies_v1_movie_proto_rawDescOnce.Do(func() {
		file_movies_v1_movie_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_movies_v1_movie_proto_rawDesc), len(file_movies_v1_movie_proto_rawDesc)))
	})
	return file_movies_v1_movie_proto_rawDescData
}

var file_movies_v1_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_movies_v1_movie_proto_goTypes = []any{
	(*MovieRequest)(nil),  // 0: movie.v1.MovieRequest
	(*MovieResponse)(nil), // 1: movie.v1.MovieResponse
}
var file_movies_v1_movie_proto_depIdxs = []int32{
	0, // 0: movie.v1.Movie.EchoMessage:input_type -> movie.v1.MovieRequest
	0, // 1: movie.v1.Movie.UnaryEcho:input_type -> movie.v1.MovieRequest
	0, // 2: movie.v1.Movie.ServerStreamingMovie:input_type -> movie.v1.MovieRequest
	0, // 3: movie.v1.Movie.ClientStreamingMovie:input_type -> movie.v1.MovieRequest
	0, // 4: movie.v1.Movie.BidirectionalStreamingMovie:input_type -> movie.v1.MovieRequest
	1, // 5: movie.v1.Movie.EchoMessage:output_type -> movie.v1.MovieResponse
	1, // 6: movie.v1.Movie.UnaryEcho:output_type -> movie.v1.MovieResponse
	1, // 7: movie.v1.Movie.ServerStreamingMovie:output_type -> movie.v1.MovieResponse
	1, // 8: movie.v1.Movie.ClientStreamingMovie:output_type -> movie.v1.MovieResponse
	1, // 9: movie.v1.Movie.BidirectionalStreamingMovie:output_type -> movie.v1.MovieResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_movies_v1_movie_proto_init() }
func file_movies_v1_movie_proto_init() {
	if File_movies_v1_movie_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_movies_v1_movie_proto_rawDesc), len(file_movies_v1_movie_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movies_v1_movie_proto_goTypes,
		DependencyIndexes: file_movies_v1_movie_proto_depIdxs,
		MessageInfos:      file_movies_v1_movie_proto_msgTypes,
	}.Build()
	File_movies_v1_movie_proto = out.File
	file_movies_v1_movie_proto_goTypes = nil
	file_movies_v1_movie_proto_depIdxs = nil
}
