// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: podcast/v2/podcast.proto

package podcast

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PodcastService_SayHello_FullMethodName = "/podcast.v1.PodcastService/SayHello"
)

// PodcastServiceClient is the client API for PodcastService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PodcastServiceClient interface {
	SayHello(ctx context.Context, in *PodcastServiceRequest, opts ...grpc.CallOption) (*PodcastServiceResponse, error)
}

type podcastServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPodcastServiceClient(cc grpc.ClientConnInterface) PodcastServiceClient {
	return &podcastServiceClient{cc}
}

func (c *podcastServiceClient) SayHello(ctx context.Context, in *PodcastServiceRequest, opts ...grpc.CallOption) (*PodcastServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PodcastServiceResponse)
	err := c.cc.Invoke(ctx, PodcastService_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodcastServiceServer is the server API for PodcastService service.
// All implementations must embed UnimplementedPodcastServiceServer
// for forward compatibility.
type PodcastServiceServer interface {
	SayHello(context.Context, *PodcastServiceRequest) (*PodcastServiceResponse, error)
	mustEmbedUnimplementedPodcastServiceServer()
}

// UnimplementedPodcastServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPodcastServiceServer struct{}

func (UnimplementedPodcastServiceServer) SayHello(context.Context, *PodcastServiceRequest) (*PodcastServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedPodcastServiceServer) mustEmbedUnimplementedPodcastServiceServer() {}
func (UnimplementedPodcastServiceServer) testEmbeddedByValue()                        {}

// UnsafePodcastServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodcastServiceServer will
// result in compilation errors.
type UnsafePodcastServiceServer interface {
	mustEmbedUnimplementedPodcastServiceServer()
}

func RegisterPodcastServiceServer(s grpc.ServiceRegistrar, srv PodcastServiceServer) {
	// If the following call pancis, it indicates UnimplementedPodcastServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PodcastService_ServiceDesc, srv)
}

func _PodcastService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodcastServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodcastServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PodcastService_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodcastServiceServer).SayHello(ctx, req.(*PodcastServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PodcastService_ServiceDesc is the grpc.ServiceDesc for PodcastService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodcastService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "podcast.v1.PodcastService",
	HandlerType: (*PodcastServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _PodcastService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "podcast/v2/podcast.proto",
}
