// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: google/v1/hello.proto

package google

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_google_v1_hello_proto protoreflect.FileDescriptor

const file_google_v1_hello_proto_rawDesc = "" +
	"\n" +
	"\x15google/v1/hello.proto\x12\tgoogle.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/api/httpbody.proto2\xb8\x01\n" +
	"\x16HttpBodyExampleService\x12O\n" +
	"\n" +
	"HelloWorld\x12\x16.google.protobuf.Empty\x1a\x14.google.api.HttpBody\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/helloworld\x12M\n" +
	"\bDownload\x12\x16.google.protobuf.Empty\x1a\x14.google.api.HttpBody\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/download0\x01B7Z5github.com/reaksa-maii/one_digital_grpc_getway/googleb\x06proto3"

var file_google_v1_hello_proto_goTypes = []any{
	(*emptypb.Empty)(nil),     // 0: google.protobuf.Empty
	(*httpbody.HttpBody)(nil), // 1: google.api.HttpBody
}
var file_google_v1_hello_proto_depIdxs = []int32{
	0, // 0: google.v1.HttpBodyExampleService.HelloWorld:input_type -> google.protobuf.Empty
	0, // 1: google.v1.HttpBodyExampleService.Download:input_type -> google.protobuf.Empty
	1, // 2: google.v1.HttpBodyExampleService.HelloWorld:output_type -> google.api.HttpBody
	1, // 3: google.v1.HttpBodyExampleService.Download:output_type -> google.api.HttpBody
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_google_v1_hello_proto_init() }
func file_google_v1_hello_proto_init() {
	if File_google_v1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_v1_hello_proto_rawDesc), len(file_google_v1_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_v1_hello_proto_goTypes,
		DependencyIndexes: file_google_v1_hello_proto_depIdxs,
	}.Build()
	File_google_v1_hello_proto = out.File
	file_google_v1_hello_proto_goTypes = nil
	file_google_v1_hello_proto_depIdxs = nil
}
