// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: google/v1/hello.proto

package google

import (
	context "context"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HttpBodyExampleService_HelloWorld_FullMethodName = "/google.v1.HttpBodyExampleService/HelloWorld"
	HttpBodyExampleService_Download_FullMethodName   = "/google.v1.HttpBodyExampleService/Download"
)

// HttpBodyExampleServiceClient is the client API for HttpBodyExampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HttpBodyExampleServiceClient interface {
	HelloWorld(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*httpbody.HttpBody, error)
	Download(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[httpbody.HttpBody], error)
}

type httpBodyExampleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHttpBodyExampleServiceClient(cc grpc.ClientConnInterface) HttpBodyExampleServiceClient {
	return &httpBodyExampleServiceClient{cc}
}

func (c *httpBodyExampleServiceClient) HelloWorld(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(httpbody.HttpBody)
	err := c.cc.Invoke(ctx, HttpBodyExampleService_HelloWorld_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpBodyExampleServiceClient) Download(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[httpbody.HttpBody], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HttpBodyExampleService_ServiceDesc.Streams[0], HttpBodyExampleService_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, httpbody.HttpBody]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HttpBodyExampleService_DownloadClient = grpc.ServerStreamingClient[httpbody.HttpBody]

// HttpBodyExampleServiceServer is the server API for HttpBodyExampleService service.
// All implementations must embed UnimplementedHttpBodyExampleServiceServer
// for forward compatibility.
type HttpBodyExampleServiceServer interface {
	HelloWorld(context.Context, *emptypb.Empty) (*httpbody.HttpBody, error)
	Download(*emptypb.Empty, grpc.ServerStreamingServer[httpbody.HttpBody]) error
	mustEmbedUnimplementedHttpBodyExampleServiceServer()
}

// UnimplementedHttpBodyExampleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHttpBodyExampleServiceServer struct{}

func (UnimplementedHttpBodyExampleServiceServer) HelloWorld(context.Context, *emptypb.Empty) (*httpbody.HttpBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HelloWorld not implemented")
}
func (UnimplementedHttpBodyExampleServiceServer) Download(*emptypb.Empty, grpc.ServerStreamingServer[httpbody.HttpBody]) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedHttpBodyExampleServiceServer) mustEmbedUnimplementedHttpBodyExampleServiceServer() {
}
func (UnimplementedHttpBodyExampleServiceServer) testEmbeddedByValue() {}

// UnsafeHttpBodyExampleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HttpBodyExampleServiceServer will
// result in compilation errors.
type UnsafeHttpBodyExampleServiceServer interface {
	mustEmbedUnimplementedHttpBodyExampleServiceServer()
}

func RegisterHttpBodyExampleServiceServer(s grpc.ServiceRegistrar, srv HttpBodyExampleServiceServer) {
	// If the following call pancis, it indicates UnimplementedHttpBodyExampleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HttpBodyExampleService_ServiceDesc, srv)
}

func _HttpBodyExampleService_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpBodyExampleServiceServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpBodyExampleService_HelloWorld_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpBodyExampleServiceServer).HelloWorld(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpBodyExampleService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HttpBodyExampleServiceServer).Download(m, &grpc.GenericServerStream[emptypb.Empty, httpbody.HttpBody]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HttpBodyExampleService_DownloadServer = grpc.ServerStreamingServer[httpbody.HttpBody]

// HttpBodyExampleService_ServiceDesc is the grpc.ServiceDesc for HttpBodyExampleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HttpBodyExampleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "google.v1.HttpBodyExampleService",
	HandlerType: (*HttpBodyExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloWorld",
			Handler:    _HttpBodyExampleService_HelloWorld_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _HttpBodyExampleService_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "google/v1/hello.proto",
}
