// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: book/v3/book.proto

package book

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Book          string                 `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRequest) Reset() {
	*x = BookRequest{}
	mi := &file_book_v3_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRequest) ProtoMessage() {}

func (x *BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_v3_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRequest.ProtoReflect.Descriptor instead.
func (*BookRequest) Descriptor() ([]byte, []int) {
	return file_book_v3_book_proto_rawDescGZIP(), []int{0}
}

func (x *BookRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookRequest) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

func (x *BookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BookRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Book          string                 `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookResponse) Reset() {
	*x = BookResponse{}
	mi := &file_book_v3_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookResponse) ProtoMessage() {}

func (x *BookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_v3_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookResponse.ProtoReflect.Descriptor instead.
func (*BookResponse) Descriptor() ([]byte, []int) {
	return file_book_v3_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookResponse) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

func (x *BookResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BookResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_book_v3_book_proto protoreflect.FileDescriptor

const file_book_v3_book_proto_rawDesc = "" +
	"\n" +
	"\x12book/v3/book.proto\x12\abook.v3\x1a\x1cgoogle/api/annotations.proto\"\x85\x01\n" +
	"\vBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04book\x18\x02 \x01(\tR\x04book\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\x86\x01\n" +
	"\fBookResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04book\x18\x02 \x01(\tR\x04book\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription2\xf4\x02\n" +
	"\x04Book\x12O\n" +
	"\vBookMessage\x12\x14.book.v3.BookRequest\x1a\x15.book.v3.BookResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v3/book\x12:\n" +
	"\tUnaryBook\x12\x14.book.v3.BookRequest\x1a\x15.book.v3.BookResponse\"\x00\x12F\n" +
	"\x13ServerStreamingBook\x12\x14.book.v3.BookRequest\x1a\x15.book.v3.BookResponse\"\x000\x01\x12F\n" +
	"\x13ClientStreamingBook\x12\x14.book.v3.BookRequest\x1a\x15.book.v3.BookResponse\"\x00(\x01\x12O\n" +
	"\x1aBidirectionalStreamingBook\x12\x14.book.v3.BookRequest\x1a\x15.book.v3.BookResponse\"\x00(\x010\x01B5Z3github.com/reaksa-maii/one_digital_grpc_getway/bookb\x06proto3"

var (
	file_book_v3_book_proto_rawDescOnce sync.Once
	file_book_v3_book_proto_rawDescData []byte
)

func file_book_v3_book_proto_rawDescGZIP() []byte {
	file_book_v3_book_proto_rawDescOnce.Do(func() {
		file_book_v3_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_v3_book_proto_rawDesc), len(file_book_v3_book_proto_rawDesc)))
	})
	return file_book_v3_book_proto_rawDescData
}

var file_book_v3_book_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_book_v3_book_proto_goTypes = []any{
	(*BookRequest)(nil),  // 0: book.v3.BookRequest
	(*BookResponse)(nil), // 1: book.v3.BookResponse
}
var file_book_v3_book_proto_depIdxs = []int32{
	0, // 0: book.v3.Book.BookMessage:input_type -> book.v3.BookRequest
	0, // 1: book.v3.Book.UnaryBook:input_type -> book.v3.BookRequest
	0, // 2: book.v3.Book.ServerStreamingBook:input_type -> book.v3.BookRequest
	0, // 3: book.v3.Book.ClientStreamingBook:input_type -> book.v3.BookRequest
	0, // 4: book.v3.Book.BidirectionalStreamingBook:input_type -> book.v3.BookRequest
	1, // 5: book.v3.Book.BookMessage:output_type -> book.v3.BookResponse
	1, // 6: book.v3.Book.UnaryBook:output_type -> book.v3.BookResponse
	1, // 7: book.v3.Book.ServerStreamingBook:output_type -> book.v3.BookResponse
	1, // 8: book.v3.Book.ClientStreamingBook:output_type -> book.v3.BookResponse
	1, // 9: book.v3.Book.BidirectionalStreamingBook:output_type -> book.v3.BookResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_book_v3_book_proto_init() }
func file_book_v3_book_proto_init() {
	if File_book_v3_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_v3_book_proto_rawDesc), len(file_book_v3_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_v3_book_proto_goTypes,
		DependencyIndexes: file_book_v3_book_proto_depIdxs,
		MessageInfos:      file_book_v3_book_proto_msgTypes,
	}.Build()
	File_book_v3_book_proto = out.File
	file_book_v3_book_proto_goTypes = nil
	file_book_v3_book_proto_depIdxs = nil
}
