// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: echo/v5/echo.proto

package echo

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_echo_v5_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_v5_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_echo_v5_echo_proto_rawDescGZIP(), []int{0}
}

func (x *GetMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_echo_v5_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_echo_v5_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_echo_v5_echo_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_echo_v5_echo_proto protoreflect.FileDescriptor

const file_echo_v5_echo_proto_rawDesc = "" +
	"\n" +
	"\x12echo/v5/echo.proto\x12\aecho.v5\x1a\x1cgoogle/api/annotations.proto\"K\n" +
	"\x11GetMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"[\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent2\x98\x01\n" +
	"\tMessaging\x12\x8a\x01\n" +
	"\n" +
	"GetMessage\x12\x1a.echo.v5.GetMessageRequest\x1a\x10.echo.v5.Message\"N\x82\xd3\xe4\x93\x02HZ+\x12)/v5/users/{user_id}/messages/{message_id}\x12\x19/v5/messages/{message_id}B5Z3github.com/reaksa-maii/one_digital_grpc_getway/echob\x06proto3"

var (
	file_echo_v5_echo_proto_rawDescOnce sync.Once
	file_echo_v5_echo_proto_rawDescData []byte
)

func file_echo_v5_echo_proto_rawDescGZIP() []byte {
	file_echo_v5_echo_proto_rawDescOnce.Do(func() {
		file_echo_v5_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_v5_echo_proto_rawDesc), len(file_echo_v5_echo_proto_rawDesc)))
	})
	return file_echo_v5_echo_proto_rawDescData
}

var file_echo_v5_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_echo_v5_echo_proto_goTypes = []any{
	(*GetMessageRequest)(nil), // 0: echo.v5.GetMessageRequest
	(*Message)(nil),           // 1: echo.v5.Message
}
var file_echo_v5_echo_proto_depIdxs = []int32{
	0, // 0: echo.v5.Messaging.GetMessage:input_type -> echo.v5.GetMessageRequest
	1, // 1: echo.v5.Messaging.GetMessage:output_type -> echo.v5.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_v5_echo_proto_init() }
func file_echo_v5_echo_proto_init() {
	if File_echo_v5_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_v5_echo_proto_rawDesc), len(file_echo_v5_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_v5_echo_proto_goTypes,
		DependencyIndexes: file_echo_v5_echo_proto_depIdxs,
		MessageInfos:      file_echo_v5_echo_proto_msgTypes,
	}.Build()
	File_echo_v5_echo_proto = out.File
	file_echo_v5_echo_proto_goTypes = nil
	file_echo_v5_echo_proto_depIdxs = nil
}
