name: Makefile CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install autotools
        run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool
      - name: Set up Make
        run: |
          make -version
