name: Build Go CI

on:
  push:
    branches: [main]
    tags:
      - "*"

  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.5
      - run: echo go version
      - name: Version
        run: |
          go version
